[[f4ncgb]]
arch = "aarch64"
git-tree-sha1 = "984987724926cf4d85b071c3c10fb9fa1d8edacf"
os = "macos"

    [[f4ncgb.download]]
    sha256 = "32283113a6f8c82b651eed9bfa0e677b231a572e7153c550c37e2404621131fd"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.3.3+0/f4ncgb.v0.3.3.aarch64-apple-darwin.tar.gz"
[[f4ncgb]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "29262c2fe3980200735ae59e82c907b30568168f"
libc = "glibc"
os = "linux"

    [[f4ncgb.download]]
    sha256 = "5f94094d206979aedab94eb728a482616c7f8094498093eaaf5ed83a7d386ece"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.3.3+0/f4ncgb.v0.3.3.aarch64-linux-gnu-cxx11.tar.gz"
[[f4ncgb]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b23ba7e6aeb5f5623b9cedc417a2dc6958b65abf"
libc = "musl"
os = "linux"

    [[f4ncgb.download]]
    sha256 = "8961ba762bc89c567249f14e3afd21231188491bc37f6681f7bfa8450228e385"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.3.3+0/f4ncgb.v0.3.3.aarch64-linux-musl-cxx11.tar.gz"
[[f4ncgb]]
arch = "aarch64"
git-tree-sha1 = "23b00a1a4f1637b15b57149aa46bb3ad3ba7eff3"
os = "freebsd"

    [[f4ncgb.download]]
    sha256 = "5065009e2dd6daf3d46f0965cdb199f47ec6fd4f034b4aee34bdf6db26753191"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.3.3+0/f4ncgb.v0.3.3.aarch64-unknown-freebsd.tar.gz"
[[f4ncgb]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e4c974eb74b408752a3451a63ca453fde1ee419d"
libc = "glibc"
os = "linux"

    [[f4ncgb.download]]
    sha256 = "745d221158c4916107ead8aaf0bcb1024373ce110f072faadcc7bd0e63b89b04"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.3.3+0/f4ncgb.v0.3.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[f4ncgb]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b8e141c3e7646ac157776d9f8a24c710b6c65e6d"
libc = "glibc"
os = "linux"

    [[f4ncgb.download]]
    sha256 = "a4a2d0487e2118c9cb8dc91de29a2cd39005387a7ff52c72bd0641f49a2c3419"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.3.3+0/f4ncgb.v0.3.3.riscv64-linux-gnu-cxx11.tar.gz"
[[f4ncgb]]
arch = "x86_64"
git-tree-sha1 = "2bddda64c78ee04525edb06f4e66b545b30d33e0"
os = "macos"

    [[f4ncgb.download]]
    sha256 = "55479e45b399302adf579a727423d072222d20cba16a4f37c43c5af5d31b2e25"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.3.3+0/f4ncgb.v0.3.3.x86_64-apple-darwin.tar.gz"
[[f4ncgb]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c717ceeaad93dbf860587a7a75d43d0b3586d05d"
libc = "glibc"
os = "linux"

    [[f4ncgb.download]]
    sha256 = "ef966c2f68166a3c5555df8700a1ee3232600a2b95c5101e395c6eac1b6dff78"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.3.3+0/f4ncgb.v0.3.3.x86_64-linux-gnu-cxx11.tar.gz"
[[f4ncgb]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c75263a8d88beac81c8e70417ab0763d0cd46684"
libc = "musl"
os = "linux"

    [[f4ncgb.download]]
    sha256 = "fc570dd6438020e4779091f4b919c7c93b3c525d99b2947b92fb3d7886d490bc"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.3.3+0/f4ncgb.v0.3.3.x86_64-linux-musl-cxx11.tar.gz"
[[f4ncgb]]
arch = "x86_64"
git-tree-sha1 = "951b5ca617c8d4b70393a7a4ad3b6becdc54bb89"
os = "freebsd"

    [[f4ncgb.download]]
    sha256 = "fd930a03690d3868aaf8c2d46ad0491a39835f7de6ebd7579b9c84f5200e581a"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.3.3+0/f4ncgb.v0.3.3.x86_64-unknown-freebsd.tar.gz"
[[f4ncgb]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "818273f70d3b8704fd36db16d389d06cd7b4ec15"
os = "windows"

    [[f4ncgb.download]]
    sha256 = "c14481dea1644c93ff58129d995cbfdaef540b873d4a1e59ab168b130c5123e0"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.3.3+0/f4ncgb.v0.3.3.x86_64-w64-mingw32-cxx11.tar.gz"
