[[f4ncgb]]
arch = "aarch64"
git-tree-sha1 = "eeac3fa29878196c98f061739c33ae45c5d2bd35"
os = "macos"

    [[f4ncgb.download]]
    sha256 = "0b8aac13b38cc3b86f215ccc373779ab05f959a1c98d5b21ccbeabf9db081020"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.300.300+0/f4ncgb.v0.300.300.aarch64-apple-darwin.tar.gz"
[[f4ncgb]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ec8005f5e75ac6d9e44f8b0bb2eaeec275e8dee0"
libc = "glibc"
os = "linux"

    [[f4ncgb.download]]
    sha256 = "8c392499cc7bc0c06f040c6e0f870853f370345adb4dca3ae29c83764d0ab032"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.300.300+0/f4ncgb.v0.300.300.aarch64-linux-gnu-cxx11.tar.gz"
[[f4ncgb]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fc759735af5646a2b5dfb85cbe3623e45cd3c0b2"
libc = "musl"
os = "linux"

    [[f4ncgb.download]]
    sha256 = "2b8b8155668ddaf11fd500f5e908cb7e76c14fcfac463361f078671e19baca43"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.300.300+0/f4ncgb.v0.300.300.aarch64-linux-musl-cxx11.tar.gz"
[[f4ncgb]]
arch = "aarch64"
git-tree-sha1 = "a027581bf566b4a31b02fd0f01309d4ad41d96dd"
os = "freebsd"

    [[f4ncgb.download]]
    sha256 = "d952f64960d15e2b5cccf7265ced8931007f84c34b22a872bed1eef7b7861cc1"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.300.300+0/f4ncgb.v0.300.300.aarch64-unknown-freebsd.tar.gz"
[[f4ncgb]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "574e699ae9e664211a66c28e07d11f67b5dd9db0"
libc = "glibc"
os = "linux"

    [[f4ncgb.download]]
    sha256 = "1fc55bb7f65c2a72917cb2efe66bab0869239aa0c139682c9c48bf2919768408"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.300.300+0/f4ncgb.v0.300.300.powerpc64le-linux-gnu-cxx11.tar.gz"
[[f4ncgb]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "64295d446cd5a5db9df7e0621a05b984fc6de2bb"
libc = "glibc"
os = "linux"

    [[f4ncgb.download]]
    sha256 = "9f98ee0b9aab5161cd530c27e3b8042a7b1050a38d0593379169019d59cd1c27"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.300.300+0/f4ncgb.v0.300.300.riscv64-linux-gnu-cxx11.tar.gz"
[[f4ncgb]]
arch = "x86_64"
git-tree-sha1 = "9baf4e34abb66ce548f40271da66b8404a672c8a"
os = "macos"

    [[f4ncgb.download]]
    sha256 = "8f77b645fba7f179591c5e79944fab87d9ac2dd03312f332d56afc738017cc0b"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.300.300+0/f4ncgb.v0.300.300.x86_64-apple-darwin.tar.gz"
[[f4ncgb]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ab7cf487833a9b1141eeb3c63abbf46f5327df91"
libc = "glibc"
os = "linux"

    [[f4ncgb.download]]
    sha256 = "f43307ff1947257a3f4038b759a6e44dcf6048eb93fe8eaa3f8a2293dbdac54d"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.300.300+0/f4ncgb.v0.300.300.x86_64-linux-gnu-cxx11.tar.gz"
[[f4ncgb]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ac1c128399d2018dd966a756ce4a8161c0e90c91"
libc = "musl"
os = "linux"

    [[f4ncgb.download]]
    sha256 = "3b911a87b843703801adde403b3a7bb1440a6ed67dfa29982132ffcaf1ef77fa"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.300.300+0/f4ncgb.v0.300.300.x86_64-linux-musl-cxx11.tar.gz"
[[f4ncgb]]
arch = "x86_64"
git-tree-sha1 = "a0d1eb43ab564ec89c11fcca69797adc613dc817"
os = "freebsd"

    [[f4ncgb.download]]
    sha256 = "df28b2fc4880aef0b22ebde478218455ddc1b2b3d9699f8833b8bdbdb535cb44"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.300.300+0/f4ncgb.v0.300.300.x86_64-unknown-freebsd.tar.gz"
[[f4ncgb]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3a0d21446eff92c4620cf65ad0a9c3fdf7b1cc76"
os = "windows"

    [[f4ncgb.download]]
    sha256 = "edd669621aa4543b0b746a61f4e303d351b9d960d54bcb41729f7636c4535426"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.300.300+0/f4ncgb.v0.300.300.x86_64-w64-mingw32-cxx11.tar.gz"
