[[f4ncgb]]
arch = "aarch64"
git-tree-sha1 = "1201b7ef8334a3eb86de2f05d2a6625b95e56066"
os = "macos"

    [[f4ncgb.download]]
    sha256 = "1834903fe40f45541934c0051603701d97b55032ecf3a23fbb001544ac4e92fe"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.300.400+0/f4ncgb.v0.300.400.aarch64-apple-darwin.tar.gz"
[[f4ncgb]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ff9fa606e8995ade01bac47cc977b9e8ea2d17e"
libc = "glibc"
os = "linux"

    [[f4ncgb.download]]
    sha256 = "296f5d94b8ed8dcb0300590886add352046ebd93c3fa81c2f1262dd0c7cf8264"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.300.400+0/f4ncgb.v0.300.400.aarch64-linux-gnu-cxx11.tar.gz"
[[f4ncgb]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ee945944343bb1f8c0af4deb4736758667a97580"
libc = "musl"
os = "linux"

    [[f4ncgb.download]]
    sha256 = "f04ba9f3ab7deccc3b85212f94ae0018f6d0c27f9ef0f5dac811895a1883e201"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.300.400+0/f4ncgb.v0.300.400.aarch64-linux-musl-cxx11.tar.gz"
[[f4ncgb]]
arch = "aarch64"
git-tree-sha1 = "e860a6f0f55e77e09313ca758b461e48eee983b6"
os = "freebsd"

    [[f4ncgb.download]]
    sha256 = "7cfb37e49345b5f15def6d085e51f783f9ff42ea6397c3f6f47886443b678688"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.300.400+0/f4ncgb.v0.300.400.aarch64-unknown-freebsd.tar.gz"
[[f4ncgb]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe27c0707bc019714ea39f03fb1b9bfa13264cd0"
libc = "glibc"
os = "linux"

    [[f4ncgb.download]]
    sha256 = "87ec8a3d274c387f72581310c3c3b37da0152b73a92b2b725e1be5226d11c083"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.300.400+0/f4ncgb.v0.300.400.powerpc64le-linux-gnu-cxx11.tar.gz"
[[f4ncgb]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "17a23c8796f4de34194f49294aaddb5176690adb"
libc = "glibc"
os = "linux"

    [[f4ncgb.download]]
    sha256 = "635d73dcb8a998328c0211314bd2733d5b7762623ff5391a15ae67851c06ce2d"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.300.400+0/f4ncgb.v0.300.400.riscv64-linux-gnu-cxx11.tar.gz"
[[f4ncgb]]
arch = "x86_64"
git-tree-sha1 = "8cfd6636a2e541986604e3874f67e1a997a07834"
os = "macos"

    [[f4ncgb.download]]
    sha256 = "912101c040a8b4e4be44010a13fac9bd4e2a23f18793ebd345564045f9c22377"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.300.400+0/f4ncgb.v0.300.400.x86_64-apple-darwin.tar.gz"
[[f4ncgb]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dd5e0ba9bcd3a4e87e2f03b23a2e4e82c6c34c36"
libc = "glibc"
os = "linux"

    [[f4ncgb.download]]
    sha256 = "3a39fada3b030a8613a4ddaaba9e97269c0f4d56bf8d37436f2e6e612b82dcc9"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.300.400+0/f4ncgb.v0.300.400.x86_64-linux-gnu-cxx11.tar.gz"
[[f4ncgb]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef2376efb7880f9e707bca31cf16df2b53df59a0"
libc = "musl"
os = "linux"

    [[f4ncgb.download]]
    sha256 = "d1a1a2db0e600db6c93e2a93f91a9a78c3255b7e29400804ab3375d6a6ed1679"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.300.400+0/f4ncgb.v0.300.400.x86_64-linux-musl-cxx11.tar.gz"
[[f4ncgb]]
arch = "x86_64"
git-tree-sha1 = "88a30a4e33cb867b4fbf5e90b8cc4275b6df4ede"
os = "freebsd"

    [[f4ncgb.download]]
    sha256 = "e88837e061834c4870ecd9e8246332cfdbd5900c0ae5f1e4dee58829bd3092f5"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.300.400+0/f4ncgb.v0.300.400.x86_64-unknown-freebsd.tar.gz"
[[f4ncgb]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2eed9300bf9b6cf5a06850f4c5b5129992d13d81"
os = "windows"

    [[f4ncgb.download]]
    sha256 = "d8bd04f9636fea4730de3e1433ca23c577448aca93a559304711399219d0fc60"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.300.400+0/f4ncgb.v0.300.400.x86_64-w64-mingw32-cxx11.tar.gz"
