[[f4ncgb]]
arch = "aarch64"
git-tree-sha1 = "d9a9a627d50353771d7993cdefd7d2441a9eb08b"
os = "macos"

    [[f4ncgb.download]]
    sha256 = "0de15c35a8adb6c664cafe5bf77cc3ce60bf521eb03bcd7135835419943cd1bb"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.3.2+0/f4ncgb.v0.3.2.aarch64-apple-darwin.tar.gz"
[[f4ncgb]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d704537ff8801633dd2f43dca71f4a3bd2744cd8"
libc = "glibc"
os = "linux"

    [[f4ncgb.download]]
    sha256 = "52af6a31e8da7a217451d890f4e4adfe12e96c96f27a2be92a03deb4402e1fcb"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.3.2+0/f4ncgb.v0.3.2.aarch64-linux-gnu-cxx11.tar.gz"
[[f4ncgb]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "86ad6b22e71cb0149adcc3df03030bb837a7cc5f"
libc = "musl"
os = "linux"

    [[f4ncgb.download]]
    sha256 = "5ea565d852fcbeaef1dff814b658373c40699026ce4769dda28e2d914eb57450"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.3.2+0/f4ncgb.v0.3.2.aarch64-linux-musl-cxx11.tar.gz"
[[f4ncgb]]
arch = "aarch64"
git-tree-sha1 = "97afbd7cb0c607112b3947765c35b35ecf14f67d"
os = "freebsd"

    [[f4ncgb.download]]
    sha256 = "3f7a6c80bccf86ee3b97e49cc788114fd7d831860f9835116a6e0f94d2d06550"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.3.2+0/f4ncgb.v0.3.2.aarch64-unknown-freebsd.tar.gz"
[[f4ncgb]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aae59e36ae7dc9fb746c783ac4660f2585ed957a"
libc = "glibc"
os = "linux"

    [[f4ncgb.download]]
    sha256 = "ea6578e4118fc3a11696fda801e3026a23b5499d35eec8e5872b4e5a4769aa61"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.3.2+0/f4ncgb.v0.3.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[f4ncgb]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "33db32a74af3c60f13fb6abf35a936f9d448f3c2"
libc = "glibc"
os = "linux"

    [[f4ncgb.download]]
    sha256 = "ac3ded238c9a97f87b79ff8ce814e1b8620545a42356cc39c7f1ed1a250b5348"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.3.2+0/f4ncgb.v0.3.2.riscv64-linux-gnu-cxx11.tar.gz"
[[f4ncgb]]
arch = "x86_64"
git-tree-sha1 = "47a6fc7a3772dba2ec90c2bac25dde7bd4b1cbe3"
os = "macos"

    [[f4ncgb.download]]
    sha256 = "8b4d9e4ccc10aab5377bf58cd5778f42272f307b3a682ef2b75b6e119fc8925b"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.3.2+0/f4ncgb.v0.3.2.x86_64-apple-darwin.tar.gz"
[[f4ncgb]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8711f96388afb778486990a7badbb471b5d1361c"
libc = "glibc"
os = "linux"

    [[f4ncgb.download]]
    sha256 = "8f2b3e9b7a84ed33ae0f0058d42d0f3484951a69834197432e7516c726d94184"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.3.2+0/f4ncgb.v0.3.2.x86_64-linux-gnu-cxx11.tar.gz"
[[f4ncgb]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9b44c193a534c5ce2cd6d39e2d50b9416b86a282"
libc = "musl"
os = "linux"

    [[f4ncgb.download]]
    sha256 = "b9b6892bfc9ca43baf049eea8ed6f90f3b3b1f728e2d235c351e7d3f47ba2036"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.3.2+0/f4ncgb.v0.3.2.x86_64-linux-musl-cxx11.tar.gz"
[[f4ncgb]]
arch = "x86_64"
git-tree-sha1 = "03a9aee0603738b3eaaca5fc98e9b3b37006c017"
os = "freebsd"

    [[f4ncgb.download]]
    sha256 = "dda649e9967d0625e3093950f66e4297f2e81e15279436961f19a887bd72193e"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.3.2+0/f4ncgb.v0.3.2.x86_64-unknown-freebsd.tar.gz"
[[f4ncgb]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "885542d495f05337dcb64e8ff57b1c0573b9f56c"
os = "windows"

    [[f4ncgb.download]]
    sha256 = "6939ff98ffec6c0dfe59b90cff0303b76bf76f2c7eec5b8a3c1a09ab008a931a"
    url = "https://github.com/JuliaBinaryWrappers/f4ncgb_jll.jl/releases/download/f4ncgb-v0.3.2+0/f4ncgb.v0.3.2.x86_64-w64-mingw32-cxx11.tar.gz"
