name = "f4ncgb_jll"
uuid = "160f184c-7e1a-5d95-af1f-70d62a450302"
version = "0.300.300+0"

[deps]
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
GMP_jll = "781609d7-10c4-51f6-84f2-b8444358ff6d"
MPFR_jll = "3a97d323-0669-5f0c-9066-3539efd106a3"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
FLINT_jll = "e134572f-a0d5-539d-bddf-3cad8db41a82"
boost_jll = "28df3c45-c428-5900-9ff8-a3135698ca75"

[compat]
JLLWrappers = "1.7.0"
julia = "1.10"
Libdl = "< 0.0.1, 1"
Artifacts = "< 0.0.1, 1"
FLINT_jll = "~301.400.000"
boost_jll = "=1.87.0"
